title: Inequality in Miami-Dade
baseURL: https://gohugo-theme-ananke.pages.dev
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Home
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
  author: 'Janet Hernandez'
  background_color_class: bg-black
  description: 'From Little Havana to South Beach: Assessing the State of the American Dream for Immigrant Communities in Miami.'
  favicon: ''
  recent_posts_number: 3
  site_logo: 'Miami-Dade Blog'
  text_color: ''

markup:
  goldmark:
    renderer:
      unsafe: true
